In [2]:
# 导入包
import numpy as np
import torch

In [3]:
x = torch.randn(3, requires_grad=True)
y = x + 2
print(y)

tensor([2.0955, 1.6534, 0.9327], grad_fn=<AddBackward0>)


In [4]:
print(x.detach().numpy().shape)
z = y ** 2 + 2
z = z.mean()
print(z)

z.backward()
print(x.grad)

(3,)
tensor(4.6649, grad_fn=<MeanBackward0>)
tensor([1.3970, 1.1023, 0.6218])


/home/sasuke/PycharmProjects/MT/venv/lib/python3.9/site-packages/torch/autograd/__init__.py:147: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:115.)
  Variable._execution_engine.run_backward(


In [5]:
weights = torch.ones(4, requires_grad=True)
for epoth in range(2):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# 优化器

In [6]:
optimizer = torch.optim.SGD(weights, lr=.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

In [ ]:
#forward pass and compute the loss
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)
y_hat = w * x
loss = (y_hat - y) ** 2
print(loss)
# backward pass
loss.backward()
print(w.grad)

# numpy 写法

In [12]:
import numpy as np


# model prediction
def forward(x):
    return w * x
    pass


# loss
def loss(y, y_pred):
    return ((y - y_pred) ** 2).mean()
    pass


# gradient
def gradient(x, y, y_pred):
    return np.dot(2 * x, y_pred - y).mean()


iters = 20
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = .0
lr = .01

for epoth in range(iters):
    prediction = forward(X)
    los = loss(Y, prediction)
    dw = gradient(X, Y, prediction)
    w -= lr * dw

    if epoth % 2 == 0:
        print(f'epoth {epoth}: loss = {los:6f}, w = {w:3f}')

print(f'Prediction before training: f(5) = {forward(5):.3f}')

epoth 0: loss = 30.000000, w = 1.200000
epoth 2: loss = 0.768000, w = 1.872000
epoth 4: loss = 0.019661, w = 1.979520
epoth 6: loss = 0.000503, w = 1.996723
epoth 8: loss = 0.000013, w = 1.999476
epoth 10: loss = 0.000000, w = 1.999916
epoth 12: loss = 0.000000, w = 1.999987
epoth 14: loss = 0.000000, w = 1.999998
epoth 16: loss = 0.000000, w = 2.000000
epoth 18: loss = 0.000000, w = 2.000000
Prediction before training: f(5) = 10.000


---
# pytorch写法

In [1]:
# 导入torch
import torch

In [38]:
t_X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
t_Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

device = torch.device('cuda:0')
lr = 0.01
iters = 50
w = torch.randn(1, dtype=torch.float32, requires_grad=True)


def forward(x):
    return w * x


def loss(y, y_pred):
    return ((y - y_pred) ** 2).mean()


def gradient(x, y, y_pred):
    return torch.mean(torch.dot(2 * x, (y_pred - y)))


for epoth in range(iters):
    y_pred = forward(t_X)
    los = loss(t_Y, y_pred)
    los.backward()
    with torch.no_grad():
        w.sub_(lr * w.grad)
    # clear the gradient
    w.grad.zero_()
    if epoth % 2 == 0:
        print(f'epoth {epoth}: loss = {los:6f}, w = {w.detach().numpy()[0]:3f}')

print(f'Prediction before training: f(5) = {forward(5).detach().numpy()[0]:3f}')

epoth 0: loss = 41.478516, w = 0.001059
epoth 2: loss = 21.652044, w = 0.555765
epoth 4: loss = 11.302504, w = 0.956540
epoth 6: loss = 5.899978, w = 1.246101
epoth 8: loss = 3.079824, w = 1.455308
epoth 10: loss = 1.607688, w = 1.606460
epoth 12: loss = 0.839223, w = 1.715667
epoth 14: loss = 0.438080, w = 1.794569
epoth 16: loss = 0.228681, w = 1.851576
epoth 18: loss = 0.119373, w = 1.892764
epoth 20: loss = 0.062313, w = 1.922522
epoth 22: loss = 0.032528, w = 1.944022
epoth 24: loss = 0.016980, w = 1.959556
epoth 26: loss = 0.008864, w = 1.970779
epoth 28: loss = 0.004627, w = 1.978888
epoth 30: loss = 0.002415, w = 1.984746
epoth 32: loss = 0.001261, w = 1.988979
epoth 34: loss = 0.000658, w = 1.992037
epoth 36: loss = 0.000344, w = 1.994247
epoth 38: loss = 0.000179, w = 1.995843
epoth 40: loss = 0.000094, w = 1.996997
epoth 42: loss = 0.000049, w = 1.997830
epoth 44: loss = 0.000026, w = 1.998432
epoth 46: loss = 0.000013, w = 1.998867
epoth 48: loss = 0.000007, w = 1.999182
Pr

---
# 使用pytorch优化器
## 设计模型
## 构建优化器和损失函数
## 训练
###     - 前向传递
###     - 后向更新
###     - 更新权重

In [1]:
import torch
import torch.nn as nn

In [2]:
t_X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
t_Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

device = torch.device('cpu')
lr = 0.01
iters = 50

n_samples, n_features = t_X.shape
input_size = n_features
output_size = n_features
# model = nn.Linear(input_size, output_size)
class LinearRegressin(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.lin = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.lin(x)

model = LinearRegressin(input_dim=input_size, output_dim=output_size)

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=lr)

for epoth in range(iters):
    y_pred = model(t_X)
    l = loss(t_Y, y_pred)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
    if epoth % 2 == 0:
        w, b = model.parameters()
        print(f'epoth {epoth}: loss = {l:6f}, w = {w[0][0]:3f}')

print(f'Prediction before training: f(5) = {model(torch.tensor([5], dtype=torch.float32)).item():3f}')

epoth 0: loss = 14.573153, w = 0.597887
epoth 2: loss = 7.115775, w = 0.916858
epoth 4: loss = 3.524106, w = 1.138845
epoth 6: loss = 1.793662, w = 1.293531
epoth 8: loss = 0.959354, w = 1.401517
epoth 10: loss = 0.556520, w = 1.477093
epoth 12: loss = 0.361439, w = 1.530177
epoth 14: loss = 0.266400, w = 1.567651
epoth 16: loss = 0.219540, w = 1.594289
epoth 18: loss = 0.195890, w = 1.613404
epoth 20: loss = 0.183429, w = 1.627296
epoth 22: loss = 0.176366, w = 1.637560
epoth 24: loss = 0.171916, w = 1.645303
epoth 26: loss = 0.168737, w = 1.651293
epoth 28: loss = 0.166181, w = 1.656062
epoth 30: loss = 0.163938, w = 1.659981
epoth 32: loss = 0.161857, w = 1.663307
epoth 34: loss = 0.159867, w = 1.666216
epoth 36: loss = 0.157932, w = 1.668834
epoth 38: loss = 0.156034, w = 1.671246
epoth 40: loss = 0.154168, w = 1.673512
epoth 42: loss = 0.152326, w = 1.675671
epoth 44: loss = 0.150509, w = 1.677755
epoth 46: loss = 0.148714, w = 1.679782
epoth 48: loss = 0.146940, w = 1.681765
Pred

/home/sasuke/PycharmProjects/MT/venv/lib/python3.9/site-packages/torch/autograd/__init__.py:147: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:115.)
  Variable._execution_engine.run_backward(
