In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

## 连接操作

In [5]:
X = torch.arange(6).reshape(2, 3)
Y = torch.Tensor(([1,2,3], [2,3,4]))

In [6]:
torch.cat((X, Y), dim=1)

tensor([[0., 1., 2., 1., 2., 3.],
        [3., 4., 5., 2., 3., 4.]])

In [7]:
torch.cat((X, Y), dim=0)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [1., 2., 3.],
        [2., 3., 4.]])

## 得到张量内数字的个数

In [11]:
X.numel(), X.shape

(6, torch.Size([2, 3]))

## reshape

In [13]:
X.reshape(X.numel(), -1).shape

torch.Size([6, 1])

# Data Preprocessing

In [5]:
import pandas as pd
import os

In [6]:
path = os.path.join('.', 'data', 'pd_data')
os.makedirs(path, exist_ok=True)

In [7]:
data_path = os.path.join(path, 'house_tiny.csv')
with open(data_path, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # Column names
    f.write('NA,Pave,127500\n')  # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


## read csv file

In [46]:
data = pd.read_csv(data_path)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [53]:
# iloc   index location
input = data.iloc[:, 0:2]
print(input.values)

[[nan 'Pave']
 [2.0 nan]
 [4.0 nan]
 [nan nan]]


NumRooms  Alley
0      True  False
1     False   True
2     False   True
3      True   True

In [20]:
input = input.fillna(input.mean())
print(input)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


/var/folders/td/6mr3pv5j4zn16h95wxk58cz00000gn/T/ipykernel_43713/1251109257.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  input = input.fillna(input.mean())


In [22]:
input = pd.get_dummies(input, dummy_na=True)
print(input)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


## pandas的axis中0代表行，1代表列

In [45]:
import numpy as np
x = np.array([[1, 2, 3], [2, 3, 4]])
x, x.shape, x.sum(axis=1), input.shape, input.values, input.sum(
    axis=1), input.values.sum(axis=1)


(array([[1, 2, 3],
        [2, 3, 4]]),
 (2, 3),
 array([6, 9]),
 (4, 3),
 array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]]),
 0    4.0
 1    3.0
 2    5.0
 3    4.0
 dtype: float64,
 array([4., 3., 5., 4.]))